### PR TITLE
feat: direct channels

### LINKED ISSUE #126: Chat with user
Blocked by #161

### PR DESCRIPTION
**Pull request by olliva**
closes #126 

need to drop current db

### CODE REVIEW

**Comment by dimaip** [comment]
:-1: Please don't merge, I think we need to re-think how we implement direct channels.
I would propose them to be particular case of general channels, just marked with `private: true`.

**Comment by Nitive** [comment]
Rebase with master please

**Comment by dimaip** [comment]
I will try to rebase it now

**Comment by dimaip** [comment]
I'm sorry, I messed up this branch, see #140

**Pull request closed without merging**
