### PR TITLE
Replace ThreadsHeader with universal Tabs component

### PR DESCRIPTION
**Pull request by Nitive**

### CODE REVIEW

**Comment by SeqviriouM** [comment]
++

**Comment by Nitive** [comment]
I get that pass data to `Tabs` component and render all `Tab` components worse than pass every `Tab` inside `Tabs` like in react-router
```
<Tabs>
  <Tab prop={value}>
  <Tab prop={anotherValue}>
</Tabs>
```

**Comment by Nitive** [comment]
Code now:
```
<Tabs
  currentTabId={this.state.currentTabId}
  changeTab={this.changeTab}
>
  <Tab id={1} name='People' />
  <Tab id={2} name='Channels' />
</Tabs>

```

**Comment by dimaip** [comment]
:+1: by reading

**Pull request merged**
